[build]
  command = "pip install -r requirements.txt && pip install -r functions/requirements.txt"
  publish = "static"
  functions = "functions"

[[redirects]]
  from = "/api/transactions"
  to = "/.netlify/functions/transactions"
  status = 200

[[redirects]]
  from = "/api/add_income"
  to = "/.netlify/functions/add_income"
  status = 200

[[redirects]]
  from = "/api/add_expense"
  to = "/.netlify/functions/add_expense"
  status = 200

[[redirects]]
  from = "/api/export_excel"
  to = "/.netlify/functions/export_excel"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200