[build]
  command = "pip install -r requirements.txt"
  publish = "static"
  functions = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200