services:
  - type: web
    name: catering-finance-tracker
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false