-- Create transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date TEXT NOT NULL,
    day TEXT NOT NULL,
    description TEXT NOT NULL,
    income DOUBLE PRECISION DEFAULT 0,
    expense DOUBLE PRECISION DEFAULT 0,
    balance DOUBLE PRECISION DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create finance_summary table
CREATE TABLE IF NOT EXISTS public.finance_summary (
    id BIGINT PRIMARY KEY,
    total_income DOUBLE PRECISION DEFAULT 0,
    total_expense DOUBLE PRECISION DEFAULT 0,
    current_balance DOUBLE PRECISION DEFAULT 0,
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Insert initial record into finance_summary if it doesn't exist
INSERT INTO public.finance_summary (id, total_income, total_expense, current_balance)
VALUES (1, 0, 0, 0)
ON CONFLICT (id) DO NOTHING;

-- Enable RLS (Row Level Security) - optional but recommended
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.finance_summary ENABLE ROW LEVEL SECURITY;